name: CMake Vcpkg

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: "${{ matrix.conf.name }} | ${{ matrix.cmake-build-type }}"
    runs-on: ${{ matrix.conf.os }}
    defaults:
      run:
        working-directory: vcpkg_project
    strategy:
      fail-fast: false
      matrix:
        conf:
          - name: Ubuntu Latest
            os: ubuntu-latest
          - name: MacOS Latest
            os: macos-latest
          - name: Windows Latest
            os: windows-latest
        cmake-build-type: [ Debug, Release ]

    steps:
      - uses: actions/checkout@v2

      - name: Create vcpkg build folder
        run: |
          mkdir -p ${{runner.workspace}}/depend_on_me/build/vcpkg_installed
          mkdir -p ${{runner.workspace}}/depend_on_me/build/_deps

      - name: Cache vcpkg
        uses: actions/cache@v2
        env:
          cache-name: vcpkg-modules
        with:
          path: |
            ${{runner.workspace}}/depend_on_me/build/vcpkg_installed
            ${{runner.workspace}}/depend_on_me/build/_deps
          key: ${{ matrix.conf.os }}-${{ matrix.cmake-build-type }}-${{ hashFiles('vcpkg_project/vcpkg.json') }}

      - name: Install Linux dependencies for Vcpkg
        if: startsWith(matrix.conf.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build pkg-config curl zip unzip tar make cmake build-essential libx11-dev libxrandr-dev libxi-dev libudev-dev libgl1-mesa-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.cmake-build-type }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.cmake-build-type }}
